# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

parameters:
  - name: RELEASE_TYPE
    displayName: "Release Type (prerelease: publish prerelease vsix to marketplace; release: publish release vsix to marketplace)"
    type: string
    default: "release"
  - name: BUILD_VERSION
    displayName: Specify which vsix to use (the ci pipeline build ID)
    type: string

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Publish
    displayName: "Publish extension to marketplace"
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-latest"
        environment: vscode-adaptive-card-release
        variables:
          - group: vscode-adaptive-card-release
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "specific"
                    project: DevDiv
                    pipeline: vscode-adaptive-card-ci
                    buildVersionToDownload: "specific"
                    buildId: ${{ parameters.BUILD_VERSION }}
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"
                - script: |
                    npm install -g @vscode/vsce
                  displayName: "Install vsce and dependencies"
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: "VSCodeAdaptivePreviewerPublishPipeline"
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      if [[ "${{ parameters.RELEASE_TYPE }}" == "release" ]]; then
                        npx vsce publish --azure-credential --packagePath $(System.ArtifactsDirectory)/Drop/vscode-adaptive-cards*.vsix
                      elif [[ "${{ parameters.RELEASE_TYPE }}" == "prerelease" ]]; then
                        npx vsce publish --pre-release --azure-credential --packagePath $(System.ArtifactsDirectory)/Drop/vscode-adaptive-cards*.vsix
                      fi
