<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>adaptive-card-previewer.output</string>
        <key>name</key>
        <string>adaptive-card-previewer-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:\[[\d\-TZ:.]*\]) (\[Info\]).*</string>
                <key>name</key>
                <string>adaptive-card-previewer.infoMessage</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.warn-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:\[[\d\-TZ:.]*\]) (\[Warning\]).*</string>
                <key>name</key>
                <string>adaptive-card-previewer.warningMessage</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.error-token</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>adaptive-card-previewer.errorMessage</string>
                <key>begin</key>
                <string>(\[Error\])</string>
                <key>end</key>
                <string>^\[[\d\-TZ:.]*\]</string>
                <key>contentName</key>
                <string>token.error-token</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>comment</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\(√\) Done\:)</string>
                <key>name</key>
                <string>adaptive-card-previewer.success</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.warn-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\(!\) Warning\:)</string>
                <key>name</key>
                <string>adaptive-card-previewer.warning</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.error-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\(×\) Error\: .*)</string>
                <key>name</key>
                <string>adaptive-card-previewer.error</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(https?:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}(\/\S*)?)</string>
                <key>name</key>
                <string>adaptive-card-previewer.hyperlink</string>
            </dict>
        </array>
    </dict>
</plist>