define([], function() {
  return {
    "Title": "AlertBannerApplicationCustomizer",
    
    // General UI
    "Save": "Gem",
    "Cancel": "Annuller",
    "Close": "Luk",
    "Edit": "Rediger",
    "Delete": "Slet",
    "Add": "Tilføj",
    "Update": "Opdater",
    "Create": "Opret",
    "Remove": "Fjern",
    "Yes": "Ja",
    "No": "Nej",
    "OK": "OK",
    "Loading": "Indlæser...",
    "Error": "Fejl",
    "Success": "Succes",
    "Warning": "Advarsel",
    "Info": "Information",
    
    // Language
    "Language": "Sprog",
    "SelectLanguage": "Vælg sprog",
    "ChangeLanguage": "Skift sprog",
    
    // Time-related
    "JustNow": "Lige nu",
    "MinutesAgo": "{0} minutter siden",
    "HoursAgo": "{0} timer siden",
    "DaysAgo": "{0} dage siden",
    
    // Alert Settings
    "AlertSettings": "Advarselsindstillinger",
    "AlertSettingsTitle": "Indstillinger for advarselsbanner",
    "AlertSettingsDescription": "Konfigurer indstillingerne for advarselsbaneret. Disse ændringer vil blive anvendt på hele webstedet.",
    "ConfigureAlertBannerSettings": "Konfigurer indstillinger for advarselsbanner",
    "Features": "Funktioner",
    "EnableUserTargeting": "Aktivér brugerretning",
    "EnableUserTargetingDescription": "Tillad advarsler at målrette specifikke brugere eller grupper",
    "EnableNotifications": "Aktivér notifikationer",
    "EnableNotificationsDescription": "Send browsernotifikationer for kritiske advarsler",
    "EnableRichMedia": "Aktivér rigt medie",
    "EnableRichMediaDescription": "Understøt billeder, videoer og rigt indhold i advarsler",
    "AlertTypesConfiguration": "Konfiguration af advarselstyper",
    "AlertTypesConfigurationDescription": "Konfigurer tilgængelige advarselstyper (JSON-format):",
    "AlertTypesPlaceholder": "Indtast JSON-konfiguration for advarselstyper...",
    "AlertTypesHelpText": "Hver advarselstype skal have: navn, ikonnavn, baggrundsfarve, tekstfarve, yderligere stilarter og prioritetsstilarter",
    "SaveSettings": "Gem indstillinger",
    "InvalidJSONError": "Ugyldigt JSON-format i konfiguration af advarselstyper. Kontroller din syntaks.",
    "ManageAlerts": "Manage Alerts",
    "AlertTypesTabTitle": "Alert Types",
    "SettingsTabTitle": "Settings",

    // Create Alert Form
    "CreateAlertSectionContentClassificationTitle": "Content Classification",
    "ContentTypeLabel": "Content Type",
    "CreateAlertSectionContentClassificationDescription": "Choose how this alert content should be classified.",
    "CreateAlertLanguageConfigurationLabel": "Language Configuration",
    "CreateAlertSingleLanguageButton": "Single Language",
    "CreateAlertMultiLanguageButton": "Multi-language",
    "CreateAlertSectionLanguageTargetingTitle": "Language Targeting",
    "CreateAlertTargetLanguageLabel": "Target Language",
    "CreateAlertSectionLanguageTargetingDescription": "Select the language that should receive this alert.",
    "CreateAlertSectionBasicInformationTitle": "Basic Information",
    "CreateAlertTitlePlaceholder": "Enter alert title",
    "CreateAlertTitleDescription": "Provide a short, descriptive title for your alert.",
    "CreateAlertDescriptionPlaceholder": "Enter alert details",
    "CreateAlertDescriptionHelp": "Use rich text to provide the full alert message. You can include links and formatting.",
    "CreateAlertConfigurationSectionTitle": "Alert Configuration",
    "CreateAlertConfigurationDescription": "Choose the visual style and importance level",
    "CreateAlertPriorityLabel": "Priority Level",
    "CreateAlertPriorityDescription": "This affects the visual styling and user attention level",
    "CreateAlertPinLabel": "Pin Alert",
    "CreateAlertPinDescription": "Pinned alerts stay at the top and are harder to dismiss",
    "CreateAlertNotificationLabel": "Notification Type",
    "CreateAlertNotificationDescription": "How users will be notified about this alert",
    "CreateAlertActionLinkSectionTitle": "Action Link (Optional)",
    "CreateAlertLinkUrlLabel": "Link URL",
    "CreateAlertLinkUrlPlaceholder": "https://example.com/more-info",
    "CreateAlertLinkUrlDescription": "Optional link for users to get more information or take action",
    "CreateAlertLinkDescriptionLabel": "Link Description",
    "CreateAlertLinkDescriptionPlaceholder": "Learn More",
    "CreateAlertLinkDescriptionDescription": "Text that will appear on the action button",
    "CreateAlertLinkDescriptionInfo": "Link descriptions will be configured per language in the Multi-Language Content section above.",
    "CreateAlertTargetSitesSectionTitle": "Target Sites",
    "CreateAlertSchedulingSectionTitle": "Scheduling (Optional)",
    "CreateAlertStartDateLabel": "Start Date & Time",
    "CreateAlertStartDateDescription": "When should this alert become visible? Leave empty to show immediately.",
    "CreateAlertEndDateLabel": "End Date & Time",
    "CreateAlertEndDateDescription": "When should this alert automatically hide? Leave empty to keep it visible until manually removed.",
    "CreateAlertPrimaryButtonLoading": "Creating Alert...",
    "CreateAlertHidePreview": "Hide Preview",
    "CreateAlertShowPreview": "Show Preview",
    "CreateAlertAutoSaving": "💾 Auto-saving...",
    "CreateAlertAutoSavedAt": "✓ Auto-saved at {0}",
    "CreateAlertSaveDraftButtonLabel": "Save as Draft",
    "CreateAlertResetFormButtonLabel": "Reset Form",
    "CreateAlertTemplatesButtonLabel": "Templates",
    "CreateAlertDraftsButtonLabel": "My Drafts ({0})",
    "CreateAlertDraftsEmptyMessage": "No drafts found. Save your work as a draft to continue later!",
    "CreateAlertLoadDraftButton": "Load Draft",
    "CreateAlertStartFromScratchButton": "Start from Scratch",
    "CreateAlertDraftTitleError": "Draft must have a title (at least 3 characters)",
    "CreateAlertAlertTypeError": "Please select an alert type before saving draft",
    "CreateAlertMultiLanguageSuccessStatus": "Multi-language alert created ({0} variants)",
    "CreateAlertCreationSuccessStatus": "Alert Created",
    "CreateAlertCreationErrorStatus": "Creation Error",
    "CreateAlertCreationResultsHeading": "Creation Results",
    "CreateAlertCreationResultSuccess": "✅ Created successfully",
    "CreateAlertCreationResultError": "❌ {0}",
    "CreateAlertDraftSaveSuccessStatus": "Draft Saved Successfully",
    "CreateAlertDraftSaveErrorStatus": "Draft Save Error",
    "CreateAlertUnknownError": "Unknown error occurred",
    "CreateAlertLanguageAtLeastOneComplete": "At least one language must have complete content (title and description)",
    "CreateAlertDefaultLanguageRequired": "Default language ({0}) must have complete content",
    "DuplicateLanguagesNotAllowed": "Duplicate language variants detected: {0}",
    "CreateAlertPreviewLanguageLabel": "Preview Language",
    "CreateAlertMultiLanguagePreviewTitle": "Multi-language Alert Title",
    "CreateAlertMultiLanguagePreviewDescription": "Multi-language alert description will appear here...",
    "CreateAlertMultiLanguagePreviewHeading": "Multi-language Alert",
    "CreateAlertMultiLanguagePreviewCurrentLanguage": "Currently previewing: {0}",
    "CreateAlertMultiLanguagePreviewAvailableLanguages": "Available in {0} language(s): {1}",
    "CreateAlertPreviewDescriptionFallback": "Alert description will appear here...",
    "CreateAlertLinkPreviewFallback": "Learn More",
    "CreateAlertPriorityLowDescription": "Generel opdatering eller lavt presserende emne.",
    "CreateAlertPriorityMediumDescription": "Vigtig information der bør ses snart.",
    "CreateAlertPriorityHighDescription": "Tidskritisk advarsel der kræver hurtig opmærksomhed.",
    "CreateAlertPriorityCriticalDescription": "Kritisk hændelse eller nedbrud som kræver øjeblikkelig handling.",
    "CreateAlertNotificationNoneDescription": "Send ingen notifikation – brugerne ser kun banneret.",
    "CreateAlertNotificationBrowserDescription": "Send en browsernotifikation sammen med banneret.",
    "CreateAlertNotificationEmailDescription": "Send en e-mail til målgruppen når advarslen udgives.",
    "CreateAlertNotificationBothDescription": "Send både browser- og e-mailnotifikationer.",
    "CreateAlertContentTypeAlertDescription": "📢 Advarsel - Live-indhold til brugere",
    "CreateAlertContentTypeTemplateDescription": "📄 Skabelon - Genanvendelig skabelon til fremtidige advarsler",
    "CreateAlertContentTypeDraftDescription": "✏️ Kladde - Igangværende arbejde",
    "CreateAlertTargetLanguageAll": "Alle understøttede sprog",
    
    // Alert Management
    "CreateAlert": "Opret advarsel",
    "EditAlert": "Rediger advarsel",
    "DeleteAlert": "Slet advarsel",
    "AlertTitle": "Advarselstitel",
    "AlertDescription": "Beskrivelse",
    "AlertType": "Advarselstype",
    "Priority": "Prioritet",
    "Status": "Status",
    "TargetSites": "Målwebsteder",
    "LinkUrl": "Link-URL",
    "LinkDescription": "Linkbeskrivelse",
    "ScheduledStart": "Planlagt start",
    "ScheduledEnd": "Planlagt slut",
    "IsPinned": "Fastgjort",
    "NotificationType": "Notifikationstype",
    
    "ManageAlertsSubtitle": "View, edit, and manage existing alerts across your sites",
    "ManageAlertsEditSelectedButtonLabel": "Edit Selected",
    "ManageAlertsDeleteSelectedButtonLabel": "Delete Selected ({0})",
    "ManageAlertsRefreshingLabel": "Refreshing...",
    "ManageAlertsHideFiltersLabel": "Hide",
    "ManageAlertsShowFiltersLabel": "Show",
    "ManageAlertsFiltersLabel": "Filters",
    "ManageAlertsLoadingTitle": "Loading alerts...",
    "ManageAlertsLoadingSubtitle": "Please wait while we fetch your alerts",
    "ManageAlertsEmptyTitle": "No Alerts Found",
    "ManageAlertsEmptyDescription": "No alerts are currently available. This might be because:",
    "ManageAlertsEmptyReasonListsMissing": "The Alert Banner lists haven't been created yet",
    "ManageAlertsEmptyReasonNoAccess": "You don't have access to the lists",
    "ManageAlertsEmptyReasonNoAlerts": "No alerts have been created yet",
    "ManageAlertsEmptyCreateFirstButton": "Create First Alert",
    "ManageAlertsFilterSummaryCount": "Showing {0} of {1} items",
    "ManageAlertsFilterSummaryLanguageGroups": "{0} multi-language groups",
    "ManageAlertsFilterAlertsLabel": "📢 Alerts ({0})",
    "ManageAlertsFilterDraftsLabel": "✏️ Drafts ({0})",
    "ManageAlertsFilterTemplatesLabel": "📄 Templates ({0})",
    "ManageAlertsFilterAllLabel": "📋 All ({0})",
    "ManageAlertsSearchPlaceholder": "🔍 Search alerts, drafts, and templates by title, description, type, priority, or author...",
    "ManageAlertsContentTypeAllOption": "📋 All Types",
    "ManageAlertsContentTypeAlertOption": "📢 Alerts",
    "ManageAlertsContentTypeDraftOption": "✏️ Drafts",
    "ManageAlertsContentTypeTemplateOption": "📄 Templates",
    "ManageAlertsPriorityAllOption": "🔘 All Priorities",
    "ManageAlertsAlertTypeAllOption": "🎨 All Types",
    "ManageAlertsStatusAllOption": "⚪ All Statuses",
    "ManageAlertsLanguageAllOption": "🌐 All Languages",
    "ManageAlertsLanguageMultiOption": "🌍 Multi-Language",
    "ManageAlertsNotificationAllOption": "📧 All Notification Types",
    "ManageAlertsNotificationNoneOption": "🚫 None - Banner only",
    "ManageAlertsNotificationBrowserOption": "🌐 Browser - Banner display",
    "ManageAlertsNotificationEmailOption": "📧 Email only - No banner",
    "ManageAlertsNotificationBothOption": "📧🌐 Browser + Email",
    "ManageAlertsCreatedDateFilterLabel": "Created Date",
    "ManageAlertsDateAllOption": "📅 All Dates",
    "ManageAlertsDateTodayOption": "📅 Today",
    "ManageAlertsDateWeekOption": "📅 This Week",
    "ManageAlertsDateMonthOption": "📅 This Month",
    "ManageAlertsDateCustomOption": "📅 Custom Range",
    "ManageAlertsFromDateLabel": "From Date",
    "ManageAlertsToDateLabel": "To Date",
    "ManageAlertsClearFiltersButton": "Clear All Filters",
    "ManageAlertsNoTitleFallback": "[No Title Available]",
    "ManageAlertsNoDescriptionFallback": "[No Description Available]",
    "ManageAlertsTemplateBadge": "📄 Template",
    "ManageAlertsAlertBadge": "📢 Alert",
    "ManageAlertsLanguageBadge": "{0} languages",
    "ManageAlertsMultiLanguageList": "🌐 Multi-language ({0})",
    "ManageAlertsAllLanguagesLabel": "🌐 All Languages",
    "ManageAlertsPublishButtonLabel": "Publish",
    "ManageAlertsCreatedLabel": "Created",
    "ManageAlertsContentClassificationDescription": "Choose whether this is a live alert, draft, or reusable template",
    "ManageAlertsLanguageConfigurationLabel": "Language Configuration",
    "ManageAlertsSingleLanguageButton": "🌐 Single Language",
    "ManageAlertsMultiLanguageButton": "🗣️ Multi-Language",
    "ManageAlertsTargetLanguageDescription": "Choose which language audience this alert targets",
    "ManageAlertsDescriptionPlaceholder": "Provide detailed information about the alert...",
    "ManageAlertsDescriptionHelp": "Use the toolbar to format your message with rich text, links, lists, emojis, and images. Manage attachments below.",
    "ManageAlertsUploadedImagesSectionTitle": "Uploaded Images",
    "ManageAlertsAlertTypeDescription": "Select the visual style and category for this alert",
    "ManageAlertsPriorityDescription": "Set the importance level—affects styling and user attention",
    "ManageAlertsPinDescription": "Pinned alerts appear at the top and are more prominent",
    "ManageAlertsNotificationMethodLabel": "Notification Method",
    "ManageAlertsNotificationDescription": "Choose how users will be notified about this alert",
    "ManageAlertsLinkDescriptionInfo": "💡 Link descriptions are configured per language in the Multi-Language Content section above.",
    "ManageAlertsTargetSitesDescription": "Choose which SharePoint sites will display this alert.",
    "ManageAlertsSchedulingDescription": "Configure when this alert will be visible. Leave dates empty for immediate activation and manual control.",
    "ManageAlertsStartDateDescription": "When this alert becomes active",
    "ManageAlertsEndDateDescription": "When this alert expires",
    "ManageAlertsScheduleSummaryTitle": "Schedule Summary",
    "ManageAlertsScheduleImmediate": "⚡ Alert is active immediately and requires manual deactivation.",
    "ManageAlertsScheduleStartOnly": "📅 Alert activates on {0} and remains active until manually deactivated.",
    "ManageAlertsScheduleEndOnly": "⏰ Alert is active immediately until {0}.",
    "ManageAlertsScheduleWindow": "📅 Active from {0} to {1}.",
    "ManageAlertsScheduleTimezone": "🌍 All times are in your local time zone ({0}).",
    "ManageAlertsSavingChangesLabel": "Saving Changes...",
    "ManageAlertsSaveChangesButton": "Save Changes",
    "ManageAlertsLivePreviewTitle": "Live Preview",
    "ManageAlertsMultiLanguagePreviewHeading": "Multi-language Preview",
    "ManageAlertsMultiLanguagePreviewCurrentLanguage": "Currently previewing: {0}",
    "ManageAlertsMultiLanguagePreviewAvailableLanguages": "Available in {0} language(s): {1}",
    "FailedToLoadSiteInformation": "Failed to load site information",
    "LanguagesUpdatedSuccessfully": "Languages updated successfully for {0}",
    "FailedToUpdateLanguages": "Failed to update languages for {0}",
    "AlertsListCreatedSuccessfully": "Alerts list created successfully on {0}",
    "FailedToCreateAlertsList": "Failed to create alerts list",
    "HomeSite": "Home Site",
    "HomeSiteDescription": "Alerts shown on all sites in the tenant",
    "HomeSiteScope": "Shown on all sites",
    "HubSite": "Hub Site",
    "HubSiteDescription": "Alerts shown on hub and connected sites",
    "HubSiteScope": "Shown on hub and connected sites",
    "CurrentSiteDescription": "Alerts shown only on this site",
    "SiteScope": "Shown only on this site",
    "ListExistsAndAccessible": "List exists and accessible",
    "ListExistsNoAccess": "List exists but no access",
    "ListNotExistsCanCreate": "List not found - can create",
    "ListNotExistsCannotCreate": "List not found - cannot create",
    "AlertListsManagement": "Alert Lists Management",
    "LoadingSiteInformation": "Loading site information...",
    "ManageAlertListsDescription": "Manage alert lists across your site hierarchy",
    "CreatingList": "Creating...",
    "CreateAlertsList": "Create Alerts List",
    "SelectLanguagesForList": "Select Languages for Alert List",
    "SelectLanguagesDescription": "Choose which languages to support for alerts on {0}. English is required and will always be included.",
    "SelectedLanguages": "Selected languages",
    "CreateWithSelectedLanguages": "Create with {0} languages",
    "ReadyForAlerts": "Ready for alerts",
    "ViewEditLanguages": "Languages",
    "ManageLanguagesForList": "Manage Languages for Alert List",
    "ManageLanguagesDescription": "Manage which languages are supported for alerts on {0}. English is required and will always be included.",
    "UpdateLanguages": "Update Languages",
    "AlertHierarchy": "Alert Display Hierarchy",
    "AlertHierarchyDescription": "Alerts are displayed based on site hierarchy: Home Site alerts appear everywhere, Hub Site alerts appear on hub and connected sites, and Site alerts appear only on the specific site.",
    // Priority Levels
    "PriorityLow": "Lav",
    "PriorityMedium": "Mellem",
    "PriorityHigh": "Høj",
    "PriorityCritical": "Kritisk",
    
    // Status Types
    "StatusActive": "Aktiv",
    "StatusExpired": "Udløbet",
    "StatusScheduled": "Planlagt",
    "StatusInactive": "Inaktiv",
    
    // Notification Types
    "NotificationNone": "Ingen",
    "NotificationBrowser": "Browser",
    "NotificationEmail": "E-mail",
    "NotificationBoth": "Begge",
    
    // Alert Types
    "AlertTypeInfo": "Information",
    "AlertTypeWarning": "Advarsel",
    "AlertTypeMaintenance": "Vedligeholdelse",
    "AlertTypeInterruption": "Afbrydelse",
    
    // User Interface
    "ShowMore": "Vis mere",
    "ShowLess": "Vis mindre",
    "ViewDetails": "Vis detaljer",
    "Expand": "Udvid",
    "Collapse": "Kollaps",
    "Preview": "Forhåndsvisning",
    "Templates": "Skabeloner",
    "CustomizeColors": "Tilpas farver",
    
    // Site Selection
    "SelectSites": "Vælg websteder",
    "CurrentSite": "Nuværende websted",
    "AllSites": "Alle websteder",
    "HubSites": "Hub-websteder",
    "RecentSites": "Seneste websteder",
    "FollowedSites": "Fulgte websteder",
    
    // Permissions and Errors
    "InsufficientPermissions": "Utilstrækkelige tilladelser til at udføre denne handling",
    "PermissionDeniedCreateLists": "Brugeren mangler tilladelser til at oprette SharePoint-lister",
    "PermissionDeniedAccessLists": "Brugeren mangler tilladelser til at få adgang til SharePoint-lister",
    "ListsNotFound": "SharePoint-lister findes ikke og kan ikke oprettes",
    "InitializationFailed": "Fejlede i at initialisere SharePoint-forbindelse",
    "ConnectionError": "Forbindelsesfejl opstod",
    "SaveError": "Der opstod en fejl under gemning",
    "LoadError": "Der opstod en fejl under indlæsning af data",
    
    // User Friendly Messages
    "NoAlertsMessage": "Ingen advarsler er i øjeblikket tilgængelige",
    "AlertsLoadingMessage": "Indlæser advarsler...",
    "AlertCreatedSuccess": "Advarsel oprettet med succes",
    "AlertUpdatedSuccess": "Advarsel opdateret med succes",
    "AlertDeletedSuccess": "Advarsel slettet med succes",
    "SettingsSavedSuccess": "Indstillinger gemt med succes",
    
    // Date and Time
    "CreatedBy": "Oprettet af",
    "CreatedOn": "Oprettet den",
    "LastModified": "Sidst ændret",
    "Never": "Aldrig",
    "Today": "I dag",
    "Yesterday": "I går",
    "Tomorrow": "I morgen",
    
    // Validation Messages
    "FieldRequired": "Dette felt er påkrævet",
    "InvalidUrl": "Indtast venligst en gyldig URL",
    "InvalidDate": "Indtast venligst en gyldig dato",
    "InvalidEmail": "Indtast venligst en gyldig e-mailadresse",
    "TitleTooLong": "Titlen er for lang (maksimum 255 tegn)",
    "DescriptionTooLong": "Beskrivelsen er for lang (maksimum 2000 tegn)",
    
    // Rich Media
    "UploadImage": "Upload billede",
    "RemoveImage": "Fjern billede",
    "ImageAltText": "Billedets alternative tekst",
    "VideoUrl": "Video-URL",
    "EmbedCode": "Indlejringskode",
    
    // Accessibility
    "CloseDialog": "Luk dialog",
    "OpenSettings": "Åbn indstillinger",
    "ExpandAlert": "Udvid advarsel",
    "CollapseAlert": "Kollaps advarsel",
    "AlertActions": "Advarselhandlinger",
    "PinAlert": "Fastgør advarsel",
    "UnpinAlert": "Løsgør advarsel",

    // Alert UI
    "AlertHeaderPriorityTooltip": "Priority: {0}",
    "AttachmentsHeader": "📎 Attachments ({0})",
    "FileSizeKilobytes": "{0} KB",
    "FileSizeMegabytes": "{0} MB",
    "AlertActionsOpenLink": "Open link",
    "AlertActionsPrevious": "Previous alert",
    "AlertActionsNext": "Next alert",
    "AlertActionsDismiss": "Dismiss alert",
    "AlertActionsHideForever": "Hide alert forever",
    "AlertCarouselCounter": "{0} of {1}",
    "DefaultAlertTypeName": "Default",
    "AlertsLoadErrorTitle": "Unable to load alerts",
    "AlertsLoadErrorFallback": "An error occurred while loading alerts. Please try refreshing the page or contact your administrator if the problem persists.",

    // Site Selector
    "SiteSelectorPermissionOwner": "Owner",
    "SiteSelectorPermissionFullControl": "Full Control",
    "SiteSelectorPermissionCanEdit": "Can Edit",
    "SiteSelectorPermissionDesigner": "Designer",
    "SiteSelectorPermissionReadOnly": "Read Only",
    "SiteSelectorLoading": "Loading available sites...",
    "SiteSelectorQuickSelectionTitle": "Quick Selection",
    "SiteSelectorCurrentSiteOnly": "Current Site Only",
    "SiteSelectorHubScope": "This Hub ({0} sites)",
    "SiteSelectorOrganizationHome": "Organization Home",
    "SiteSelectorRecentSites": "Recent Sites ({0})",
    "SiteSelectorSearchPlaceholder": "Search sites by name or URL...",
    "SiteSelectorFiltersLabel": "Filters",
    "SiteSelectorShowWritable": "Show only sites where I can create alerts",
    "SiteSelectorSiteTypeLabel": "Site Type:",
    "SiteSelectorSiteTypeAll": "All Sites",
    "SiteSelectorSiteTypeHub": "Hub Sites",
    "SiteSelectorSiteTypeTeam": "Team Sites",
    "SiteSelectorSiteTypeCommunication": "Communication Sites",
    "SiteSelectorSiteTypeHome": "Home Sites",
    "SiteSelectorNoResultsTitle": "No sites found",
    "SiteSelectorNoResultsDescription": "Try adjusting your search terms or filters.",
    "SiteSelectorWritableFilterHint": "You may need to disable the 'writable only' filter to see more sites.",
    "SiteSelectorSiteSingular": "site",
    "SiteSelectorSitePlural": "sites",
    "SiteSelectorSelected": "selected",
    "SiteSelectorMaxSelection": "(max {0})",

    // Multi-Language Content Editor
    "MultiLanguageEditorAddLanguagesLabel": "Add Languages:",
    "MultiLanguageEditorAllLanguagesAdded": "All available languages have been added",
    "MultiLanguageEditorIncompleteBadge": "Incomplete",
    "MultiLanguageEditorRemoveButton": "Remove",
    "MultiLanguageEditorTitleLabel": "Title",
    "MultiLanguageEditorTitlePlaceholder": "Enter alert title in {0}...",
    "MultiLanguageEditorDescriptionLabel": "Description",
    "MultiLanguageEditorDescriptionPlaceholder": "Enter alert description in {0}...",
    "MultiLanguageEditorLinkDescriptionLabel": "Link Description",
    "MultiLanguageEditorLinkDescriptionPlaceholder": "Enter link description in {0}...",
    "MultiLanguageEditorNoLanguagesTitle": "No Languages Selected",
    "MultiLanguageEditorNoLanguagesDescription": "Add languages above to create multi-language content",
    "MultiLanguageEditorSummaryTitle": "Content Summary:",
    "MultiLanguageEditorSummaryComplete": "✓ Complete",
    "MultiLanguageEditorSummaryIncomplete": "⚠ Incomplete",
    "MultiLanguageEditorLanguageCount": "{0} languages",
    "MultiLanguageEditorFallbackLabel": "Use this language as fallback for other users",
    "TranslationStatusLabel": "Translation Status",
    "TranslationStatusDescription": "Track the state of this language variant",
    "TranslationStatusDraft": "Draft",
    "TranslationStatusInReview": "In Review",
    "TranslationStatusApproved": "Approved",
    "LanguagePolicyInheritanceHint": "Empty fields will inherit from {0}.",

    // Language Policy
    "LanguagePolicyTitle": "Language Policy",
    "LanguagePolicyDescription": "Configure translation rules, fallback behavior, and workflow requirements for multi-language alerts.",
    "LanguagePolicyFallbackLanguageLabel": "Fallback Language",
    "LanguagePolicyFallbackLanguageDescription": "Used when a user’s preferred language is not available.",
    "LanguagePolicyFallbackTenantDefault": "Tenant default language",
    "LanguagePolicyCompletenessRuleLabel": "Translation Completeness",
    "LanguagePolicyCompletenessRuleDescription": "Choose how complete translations must be before saving or publishing.",
    "LanguagePolicyCompletenessAll": "Require all selected languages to be complete",
    "LanguagePolicyCompletenessAtLeastOne": "Require at least one complete language",
    "LanguagePolicyCompletenessDefault": "Require the default language to be complete",
    "LanguagePolicyRequireLinkDescriptionLabel": "Require link descriptions when a URL is provided",
    "LanguagePolicyRequireLinkDescriptionDescription": "Ensures localized link descriptions are provided for each language when links are used.",
    "LanguagePolicyPreventDuplicatesLabel": "Prevent duplicate language variants",
    "LanguagePolicyPreventDuplicatesDescription": "Block saving when the same language is added more than once.",
    "LanguagePolicyInheritanceEnable": "Enable field inheritance",
    "LanguagePolicyInheritanceDescription": "Allow missing fields to inherit from the fallback language.",
    "LanguagePolicyInheritanceTitleField": "Inherit Title",
    "LanguagePolicyInheritanceDescriptionField": "Inherit Description",
    "LanguagePolicyInheritanceLinkDescriptionField": "Inherit Link Description",
    "LanguagePolicyWorkflowEnable": "Enable translation workflow",
    "LanguagePolicyWorkflowDescription": "Track translation status for each language variant.",
    "LanguagePolicyWorkflowDefaultStatusLabel": "Default Translation Status",
    "LanguagePolicyWorkflowRequireApproved": "Require Approved status to display",
    "LanguagePolicyWorkflowRequireApprovedDescription": "Hide translation variants that are not approved.",
    "LanguagePolicySaveButton": "Save Language Policy",
    "LanguagePolicySaving": "Saving...",
    "LanguagePolicySavedSuccess": "Language policy saved",
    "LanguagePolicySavedFailed": "Failed to save language policy",

    // Language Manager
    "LanguageManagerTitle": "Multi-Language Field Management",
    "LanguageManagerDescription": "Select languages to add multi-language content fields to your alert lists. Fields will be created for Title, Description, and Link Description in each selected language.",
    "LanguageManagerAvailableLanguages": "Available Languages",
    "LanguageManagerActiveCount": "{0} active",
    "LanguageManagerActiveCountWithPending": "{0} active, {1} updating",
    "LanguageManagerLoading": "Loading...",
    "LanguageManagerLoadingSupport": "Loading language support...",
    "LanguageManagerUpdating": "Updating...",
    "LanguageManagerActive": "Active",
    "LanguageManagerLoadFailedDefault": "Could not load language support. Using site default: {0}",
    "LanguageManagerDefaultLanguageProtected": "{0} is the site's default language and cannot be removed.",
    "LanguageManagerAddedSuccess": "Added {0} language support successfully!",
    "LanguageManagerRemovedSuccess": "Removed {0} language support and columns.",
    "LanguageManagerUpdateFailed": "Failed to update language support for {0}.",

    // Alert Templates
    "AlertTemplatesTemplateDescription": "Template based on \"{0}\"",
    "AlertTemplatesCategoryAll": "All Templates",
    "AlertTemplatesCategoryMaintenance": "Maintenance",
    "AlertTemplatesCategoryInformation": "Information",
    "AlertTemplatesCategoryEmergency": "Emergency",
    "AlertTemplatesCategoryInterruption": "Interruption",
    "AlertTemplatesCategoryTraining": "Training",
    "AlertTemplatesCategoryAnnouncements": "Announcements",
    "AlertTemplatesHeaderTitle": "Choose a Template",
    "AlertTemplatesHeaderDescription": "Start with a pre-configured template and customize it to your needs",
    "AlertTemplatesSearchPlaceholder": "Search templates...",
    "AlertTemplatesUseTemplate": "Use Template →",
    "AlertTemplatesLoadingTitle": "Loading Templates...",
    "AlertTemplatesLoadingDescription": "Fetching templates from SharePoint",
    "AlertTemplatesNoResultsTitle": "No templates found",
    "AlertTemplatesNoResultsDescription": "Try adjusting your search terms or category filter",
    "AlertTemplatesEmptyTitle": "No templates available",
    "AlertTemplatesEmptyDescription": "Templates will be created automatically when alert lists are set up",
    "AlertTemplatesPinnedBadge": "PINNED",
    "AlertTemplatesNotifyBadge": "NOTIFY",
    "AlertTemplatesDefaultLinkDescription": "Learn more",

    // Attachments
    "AttachmentManagerDeleteConfirm": "Are you sure you want to delete \"{0}\"?",
    "AttachmentManagerTitle": "Attachments",
    "AttachmentManagerUploadingLabel": "Uploading...",
    "AttachmentManagerAddFilesButton": "Add Files",
    "AttachmentManagerSaveNotice": "Save the alert first to add attachments",
    "AttachmentManagerDropZoneInstruction": "Drag and drop files here or click \"Add Files\" button",
    "AttachmentManagerDropZoneHint": "{0} | Max {1}MB per file",
    "AttachmentManagerProgressTitle": "Uploading files...",
    "AttachmentManagerStatusCompleted": "✓ Completed",
    "AttachmentManagerStatusFailed": "✗ Failed",
    "AttachmentManagerDownloadTitle": "Download",
    "AttachmentManagerDeleteTitle": "Delete",
    "AttachmentManagerHelpText": "Allowed formats: {0} | Max size: {1}MB per file",
    "AttachmentManagerDeleteError": "Failed to delete attachment. Please try again.",
    "AttachmentManagerSaveAlertFirst": "Please save the alert first before adding attachments.",
    "AttachmentManagerUploadFailed": "Failed to upload some attachments. Please try again.",
    "AttachmentManagerInvalidFormat": "{0}: Invalid file format (allowed: {1})",
    "AttachmentManagerFileTooLarge": "{0}: File size exceeds {1}MB limit ({2}MB)",

    // Image Manager
    "ImageManagerDeleteConfirm": "Delete \"{0}\"? This cannot be undone.",
    "ImageManagerLoading": "Loading images...",
    "ImageManagerError": "Error: {0}",
    "ImageManagerEmpty": "No images uploaded yet",
    "ImageManagerHeaderTitle": "Uploaded Images ({0})",
    "ImageManagerCopyUrl": "Copy URL",
    "ImageManagerDeleteError": "Failed to delete image: {0}",
    "ImageManagerCopySuccess": "Image URL copied to clipboard!",
    "ImageManagerCopyError": "Failed to copy URL",
    "ImageUploadFailure": "Image upload failed. Please try again.",
    "ImageUploadInvalidFile": "Please select a valid image file (PNG, JPG, GIF, or WebP).",

    // Repair Dialog
    "RepairDialogWarningMessage": "This action will modify your SharePoint list structure.",
    "RepairDialogActionsIntro": "The repair process will:",
    "RepairDialogRemoveColumns": "Remove outdated columns that are no longer needed",
    "RepairDialogAddColumns": "Add missing columns with current definitions",
    "RepairDialogUpdateColumns": "Update existing columns to match the latest schema",
    "RepairDialogProtectData": "Preserve all existing data and language-specific columns",
    "RepairDialogSafeProcess": "Safe Process:",
    "RepairDialogSafeProcessDescription": "This repair is designed to be non-destructive. Your existing alert data will be preserved, and language-specific columns will be kept intact.",
    "RepairDialogProgressTitle": "Repairing Alerts List...",
    "RepairDialogProgressDescription": "Please wait while we update your list structure. This may take a few minutes.",
    "RepairDialogResultSuccessTitle": "Repair Completed!",
    "RepairDialogResultFailureTitle": "Repair Failed",
    "RepairDialogRemovedColumnsTitle": "Removed Columns ({0})",
    "RepairDialogAddedColumnsTitle": "Added/Updated Columns ({0})",
    "RepairDialogWarningsTitle": "Warnings ({0})",
    "RepairDialogErrorsTitle": "Errors ({0})",
    "RepairDialogStartButton": "Start Repair",
    "RepairDialogCancelButton": "Cancel",
    "RepairDialogInProgressButton": "Repairing...",
    "RepairDialogCloseButton": "Close",
    "RepairDialogDialogTitleSuccess": "Repair Completed Successfully",
    "RepairDialogDialogTitleIssues": "Repair Completed with Issues",
    "RepairDialogDialogTitleProgress": "Repairing Alerts List",
    "RepairDialogTitle": "Repair Alerts List",
    "RepairDialogPleaseWait": "Please wait...",

    // Color Picker
    "ColorPickerSelectedColorAria": "Selected color: {0}",
    "ColorPickerPresetColorsTitle": "Preset Colors",
    "ColorPickerCustomColorTitle": "Custom Color",
    "ColorPickerApplyButton": "Apply",
    "ColorPickerSelectColorAria": "Select color {0}",

    // Emoji Picker
    "EmojiPickerButtonTitle": "Add emoji",
    "EmojiPickerButtonLabel": "Add Emoji",
    "EmojiPickerSearchPlaceholder": "Search emoji...",

    // Rich Text Editor
    "RichTextEditorLoadError": "Unable to load Rich Text editor",
    "RichTextEditorPlaceholder": "Enter your message...",

    // Progress Indicator
    "ProgressIndicatorTitle": "Progress",
    "ProgressIndicatorFailedSummary": "{0} of {1} steps failed",
    "ProgressIndicatorCompletedSummary": "{0} of {1} steps completed",
    "ProgressIndicatorError": "Error: {0}",

    // Alert Preview
    "AlertPreviewDefaultTitle": "Alert Title",
    "AlertPreviewDefaultDescription": "Alert description will appear here...",
    "AlertPreviewPinnedBadge": "📌 PINNED",
    "AlertPreviewTypeLabel": "Type:",
    "AlertPreviewPriorityLabel": "Priority:",
    "AlertPreviewBackgroundLabel": "Background:",
    "AlertPreviewTextColorLabel": "Text Color:",
    "AlertPreviewIconLabel": "Icon:",
    "AlertPreviewLinkPrefix": "🔗 {0}",

    // Error Boundary
    "ErrorBoundaryHeader": "Something went wrong in {0}",
    "ErrorBoundaryFallbackMessage": "An unexpected error occurred",
    "ErrorBoundaryIdLabel": "Error ID: {0}",
    "ErrorBoundaryRetryButton": "Try Again",
    "ErrorBoundaryAttemptsLeft": "attempts left",
    "ErrorBoundaryCopyButton": "Copy Error Details",
    "ErrorBoundaryReloadButton": "Reload Page",
    "ErrorBoundaryDevDetailsTitle": "Development Error Details",
    
    // Permission Status
    "PermissionStatusChecking": "Checking permissions...",
    "PermissionStatusAllGranted": "All required permissions are granted",
    "PermissionStatusMissingTitle": "Additional permissions required",
    "PermissionStatusSitesWriteRequired": "Sites.ReadWrite.All",
    "PermissionStatusSitesWriteDescription": "Required to create and manage alert lists across sites",
    "PermissionStatusMailRequired": "Mail.Send",
    "PermissionStatusMailDescription": "Required to send email notifications for critical alerts",
    "PermissionStatusShowDetails": "Show details",
    "PermissionStatusHideDetails": "Hide details",
    "PermissionStatusMissingList": "Missing permissions",
    "PermissionStatusAdminAction": "As a site admin, you can grant these permissions:",
    "PermissionStatusGrantPermissions": "Grant permissions in Azure AD",
    "PermissionStatusContactAdmin": "Please contact your SharePoint administrator to grant these permissions.",
    
    "ManageAlertsCrossSiteImagesNotice": "Images from other sites may not display due to cross-site permissions."
  }
});
