define([], function() {
  return {
    "Title": "AlertBannerApplicationCustomizer",
    
    // General UI
    "Save": "Tallenna",
    "Cancel": "Peruuta",
    "Close": "Sulje",
    "Edit": "Muokkaa",
    "Delete": "Poista",
    "Add": "Lisää",
    "Update": "Päivitä",
    "Create": "Luo",
    "Remove": "Poista",
    "Yes": "Kyllä",
    "No": "Ei",
    "OK": "OK",
    "Loading": "Ladataan...",
    "Error": "Virhe",
    "Success": "Onnistui",
    "Warning": "Varoitus",
    "Info": "Tieto",
    
    // Language
    "Language": "Kieli",
    "SelectLanguage": "Valitse kieli",
    "ChangeLanguage": "Vaihda kieli",
    
    // Time-related
    "JustNow": "Juuri nyt",
    "MinutesAgo": "{0} minuuttia sitten",
    "HoursAgo": "{0} tuntia sitten",
    "DaysAgo": "{0} päivää sitten",
    
    // Alert Settings
    "AlertSettings": "Hälytysasetukset",
    "AlertSettingsTitle": "Hälytysbannerin asetukset",
    "AlertSettingsDescription": "Määritä hälytysbannerin asetukset. Nämä muutokset koskevat koko sivustoa.",
    "ConfigureAlertBannerSettings": "Määritä hälytysbannerin asetukset",
    "Features": "Ominaisuudet",
    "EnableUserTargeting": "Ota käyttöön käyttäjäkohdistus",
    "EnableUserTargetingDescription": "Salli hälytysten kohdistaminen tiettyihin käyttäjiin tai ryhmiin",
    "EnableNotifications": "Ota ilmoitukset käyttöön",
    "EnableNotificationsDescription": "Lähetä selainilmoituksia kriittisistä hälytyksistä",
    "EnableRichMedia": "Ota rikas media käyttöön",
    "EnableRichMediaDescription": "Tuki kuville, videoille ja rikkaalle sisällölle hälytyksissa",
    "AlertTypesConfiguration": "Hälytystyyppien määrittäminen",
    "AlertTypesConfigurationDescription": "Määritä käytettävissä olevat hälytystyypit (JSON-muoto):",
    "AlertTypesPlaceholder": "Syötä hälytystyyppien JSON-määritys...",
    "AlertTypesHelpText": "Jokaisella hälytystyypillä tulee olla: nimi, kuvakenimi, taustavan väri, tekstin väri, lisätyylit ja prioriteettityylit",
    "SaveSettings": "Tallenna asetukset",
    "InvalidJSONError": "Virheellinen JSON-muoto hälytystyyppien määrityksessä. Tarkista syntaksi.",
    "ManageAlerts": "Manage Alerts",
    "AlertTypesTabTitle": "Alert Types",
    "SettingsTabTitle": "Settings",

    // Create Alert Form
    "CreateAlertSectionContentClassificationTitle": "Content Classification",
    "ContentTypeLabel": "Content Type",
    "CreateAlertSectionContentClassificationDescription": "Choose how this alert content should be classified.",
    "CreateAlertLanguageConfigurationLabel": "Language Configuration",
    "CreateAlertSingleLanguageButton": "Single Language",
    "CreateAlertMultiLanguageButton": "Multi-language",
    "CreateAlertSectionLanguageTargetingTitle": "Language Targeting",
    "CreateAlertTargetLanguageLabel": "Target Language",
    "CreateAlertSectionLanguageTargetingDescription": "Select the language that should receive this alert.",
    "CreateAlertSectionBasicInformationTitle": "Basic Information",
    "CreateAlertTitlePlaceholder": "Enter alert title",
    "CreateAlertTitleDescription": "Provide a short, descriptive title for your alert.",
    "CreateAlertDescriptionPlaceholder": "Enter alert details",
    "CreateAlertDescriptionHelp": "Use rich text to provide the full alert message. You can include links and formatting.",
    "CreateAlertConfigurationSectionTitle": "Alert Configuration",
    "CreateAlertConfigurationDescription": "Choose the visual style and importance level",
    "CreateAlertPriorityLabel": "Priority Level",
    "CreateAlertPriorityDescription": "This affects the visual styling and user attention level",
    "CreateAlertPinLabel": "Pin Alert",
    "CreateAlertPinDescription": "Pinned alerts stay at the top and are harder to dismiss",
    "CreateAlertNotificationLabel": "Notification Type",
    "CreateAlertNotificationDescription": "How users will be notified about this alert",
    "CreateAlertActionLinkSectionTitle": "Action Link (Optional)",
    "CreateAlertLinkUrlLabel": "Link URL",
    "CreateAlertLinkUrlPlaceholder": "https://example.com/more-info",
    "CreateAlertLinkUrlDescription": "Optional link for users to get more information or take action",
    "CreateAlertLinkDescriptionLabel": "Link Description",
    "CreateAlertLinkDescriptionPlaceholder": "Learn More",
    "CreateAlertLinkDescriptionDescription": "Text that will appear on the action button",
    "CreateAlertLinkDescriptionInfo": "Link descriptions will be configured per language in the Multi-Language Content section above.",
    "CreateAlertTargetSitesSectionTitle": "Target Sites",
    "CreateAlertSchedulingSectionTitle": "Scheduling (Optional)",
    "CreateAlertStartDateLabel": "Start Date & Time",
    "CreateAlertStartDateDescription": "When should this alert become visible? Leave empty to show immediately.",
    "CreateAlertEndDateLabel": "End Date & Time",
    "CreateAlertEndDateDescription": "When should this alert automatically hide? Leave empty to keep it visible until manually removed.",
    "CreateAlertPrimaryButtonLoading": "Creating Alert...",
    "CreateAlertHidePreview": "Hide Preview",
    "CreateAlertShowPreview": "Show Preview",
    "CreateAlertAutoSaving": "💾 Auto-saving...",
    "CreateAlertAutoSavedAt": "✓ Auto-saved at {0}",
    "CreateAlertSaveDraftButtonLabel": "Save as Draft",
    "CreateAlertResetFormButtonLabel": "Reset Form",
    "CreateAlertTemplatesButtonLabel": "Templates",
    "CreateAlertPreviousAlertsButtonLabel": "Previous Alerts ({0})",
    "CreateAlertDraftsButtonLabel": "My Drafts ({0})",
    "CreateAlertDraftsEmptyMessage": "No drafts found. Save your work as a draft to continue later!",
    "CreateAlertPreviousAlertsEmptyMessage": "No recent alerts found on this site yet.",
    "CreateAlertLoadDraftButton": "Load Draft",
    "CreateAlertUsePreviousButton": "Use Alert",
    "CreateAlertStartFromScratchButton": "Start from Scratch",
    "CreateAlertDraftTitleError": "Draft must have a title (at least 3 characters)",
    "CreateAlertAlertTypeError": "Please select an alert type before saving draft",
    "CreateAlertMultiLanguageSuccessStatus": "Multi-language alert created ({0} variants)",
    "CreateAlertMultiLanguageSuccessTitle": "Alerts Created",
    "CreateAlertCreationSuccessStatus": "Alert Created",
    "CreateAlertCreationSuccessTitle": "Alert Created",
    "CreateAlertCreationErrorStatus": "Creation Error",
    "CreateAlertCreationErrorTitle": "Creation Failed",
    "CreateAlertCreationResultsHeading": "Creation Results",
    "CreateAlertCreationResultSuccess": "✅ Created successfully",
    "CreateAlertCreationResultError": "❌ {0}",
    "CreateAlertCreationRetryButton": "Retry Create Alert",
    "CreateAlertDraftSaveSuccessStatus": "Draft Saved Successfully",
    "CreateAlertDraftSaveErrorStatus": "Draft Save Error",
    "CreateAlertUnknownError": "Unknown error occurred",
    "CreateAlertLanguageRequired": "At least one language must be configured",
    "CreateAlertLanguageTitleRequired": "Title is required for {0}",
    "CreateAlertLanguageDescriptionRequired": "Description is required for {0}",
    "CreateAlertLanguageLinkDescriptionRequired": "Link description is required for {0} when URL is provided",
    "CreateAlertLanguageAtLeastOneComplete": "At least one language must have complete content (title and description)",
    "CreateAlertDefaultLanguageRequired": "Default language ({0}) must have complete content",
    "DuplicateLanguagesNotAllowed": "Duplicate language variants detected: {0}",
    "CreateAlertPreviewLanguageLabel": "Preview Language",
    "CreateAlertMultiLanguagePreviewTitle": "Multi-language Alert Title",
    "CreateAlertMultiLanguagePreviewDescription": "Multi-language alert description will appear here...",
    "CreateAlertMultiLanguagePreviewHeading": "Multi-language Alert",
    "CreateAlertMultiLanguagePreviewCurrentLanguage": "Currently previewing: {0}",
    "CreateAlertMultiLanguagePreviewAvailableLanguages": "Available in {0} language(s): {1}",
    "CreateAlertPreviewDescriptionFallback": "Alert description will appear here...",
    "CreateAlertLinkPreviewFallback": "Learn More",
    "CreateAlertPriorityLowDescription": "Yleinen päivitys tai matalan kiireellisyyden tieto.",
    "CreateAlertPriorityMediumDescription": "Tärkeä tieto, joka tulisi nähdä pian.",
    "CreateAlertPriorityHighDescription": "Aikakriittinen hälytys, joka vaatii nopeaa huomiota.",
    "CreateAlertPriorityCriticalDescription": "Kriittinen tapaus tai katkos, joka vaatii välitöntä toimintaa.",
    "CreateAlertNotificationNoneDescription": "Älä lähetä ilmoitusta – käyttäjät näkevät vain bannerin.",
    "CreateAlertNotificationBrowserDescription": "Lähetä bannerin lisäksi selaimen ilmoitus.",
    "CreateAlertNotificationEmailDescription": "Lähetä sähköposti kohdekäyttäjille, kun hälytys julkaistaan.",
    "CreateAlertNotificationBothDescription": "Lähetä sekä selaimen että sähköpostin ilmoitukset.",
    "CreateAlertContentTypeAlertDescription": "📢 Hälytys - Live-sisältö käyttäjille",
    "CreateAlertContentTypeTemplateDescription": "📄 Malli - Uudelleenkäytettävä malli tuleville hälytyksille",
    "CreateAlertContentTypeDraftDescription": "✏️ Luonnos - Keskeneräinen työ",
    "CreateAlertTargetLanguageAll": "Kaikki tuetut kielet",
    "CreateAlertWizardContentStep": "Content",
    "CreateAlertWizardAudienceStep": "Actions & Media",
    "CreateAlertWizardPublishStep": "Publish",
    "CreateAlertWizardStepComplete": "Ready",
    "CreateAlertWizardStepIncomplete": "Needs input",
    "CreateAlertWizardBackButton": "Back",
    "CreateAlertWizardNextButton": "Next",
    "CreateAlertPublishSummaryTitle": "Confirm Alert Creation",
    "CreateAlertSchedulePresetNow": "Start Now",
    "CreateAlertSchedulePresetEndOfDay": "End of Day",
    "CreateAlertSchedulePresetPlusWeek": "End in 1 Week",
    "CreateAlertPriorityInheritedMessage": "Priority default was applied from alert type: {0}.",
    "CreateAlertImageManagerHint": "Set a title or enable multi-language to initialize an image folder.",
    "CreateAlertCopilotUnavailableMessage": "Copilot is enabled but unavailable for this account or tenant.",
    "CreateAlertUnsavedChangesTitle": "Discard Unsaved Changes?",
    "CreateAlertUnsavedChangesMessage": "You have unsaved create-alert changes. Leave this tab and discard them?",
    "CreateAlertDiscardChangesButton": "Discard Changes",
    "CreateAlertKeepEditingButton": "Keep Editing",
    
    // Alert Management
    "CreateAlert": "Luo hälytys",
    "EditAlert": "Muokkaa hälytystä",
    "DeleteAlert": "Poista hälytys",
    "AlertTitle": "Hälytyksen otsikko",
    "AlertDescription": "Kuvaus",
    "AlertType": "Hälytystyyppi",
    "Priority": "Prioriteetti",
    "Status": "Tila",
    "TargetSites": "Kohdistetut sivustot",
    "LinkUrl": "Linkin URL",
    "LinkDescription": "Linkin kuvaus",
    "ScheduledStart": "Ajastettu alku",
    "ScheduledEnd": "Ajastettu loppu",
    "IsPinned": "Kiinnitetty",
    "NotificationType": "Ilmoitustyyppi",
    
    "ManageAlertsSubtitle": "View, edit, and manage existing alerts across your sites",
    "ManageAlertsUnsavedChangesTitle": "Discard Unsaved Changes?",
    "ManageAlertsUnsavedChangesMessage": "You have unsaved manage-alert changes. Leave this view and discard them?",
    "ManageAlertsDiscardChangesButton": "Discard Changes",
    "ManageAlertsKeepEditingButton": "Keep Editing",
    "ManageAlertsEditSelectedButtonLabel": "Edit Selected",
    "ManageAlertsDeleteSelectedButtonLabel": "Delete Selected ({0})",
    "ManageAlertsRefreshingLabel": "Refreshing...",
    "ManageAlertsHideFiltersLabel": "Hide",
    "ManageAlertsShowFiltersLabel": "Show",
    "ManageAlertsFiltersLabel": "Filters",
    "ManageAlertsLoadingTitle": "Loading alerts...",
    "ManageAlertsLoadingSubtitle": "Please wait while we fetch your alerts",
    "ManageAlertsEmptyTitle": "No Alerts Found",
    "ManageAlertsEmptyDescription": "No alerts are currently available. This might be because:",
    "ManageAlertsEmptyReasonListsMissing": "The Alert Banner lists haven't been created yet",
    "ManageAlertsEmptyReasonNoAccess": "You don't have access to the lists",
    "ManageAlertsEmptyReasonNoAlerts": "No alerts have been created yet",
    "ManageAlertsEmptyCreateFirstButton": "Create First Alert",
    "ManageAlertsFilterSummaryCount": "Showing {0} of {1} items",
    "ManageAlertsFilterSummaryLanguageGroups": "{0} multi-language groups",
    "ManageAlertsFilterAlertsLabel": "📢 Alerts ({0})",
    "ManageAlertsFilterDraftsLabel": "✏️ Drafts ({0})",
    "ManageAlertsFilterTemplatesLabel": "📄 Templates ({0})",
    "ManageAlertsFilterAllLabel": "📋 All ({0})",
    "ManageAlertsSearchLabel": "Search alerts",
    "ManageAlertsSearchPlaceholder": "🔍 Search alerts, drafts, and templates by title, description, type, priority, or author...",
    "ManageAlertsContentTypeAllOption": "📋 All Types",
    "ManageAlertsContentTypeAlertOption": "📢 Alerts",
    "ManageAlertsContentTypeDraftOption": "✏️ Drafts",
    "ManageAlertsContentTypeTemplateOption": "📄 Templates",
    "ManageAlertsPriorityAllOption": "🔘 All Priorities",
    "ManageAlertsAlertTypeAllOption": "🎨 All Types",
    "ManageAlertsStatusAllOption": "⚪ All Statuses",
    "ManageAlertsLanguageAllOption": "🌐 All Languages",
    "ManageAlertsLanguageMultiOption": "🌍 Multi-Language",
    "ManageAlertsNotificationAllOption": "📧 All Notification Types",
    "ManageAlertsNotificationNoneOption": "🚫 None - Banner only",
    "ManageAlertsNotificationBrowserOption": "🌐 Browser - Banner display",
    "ManageAlertsNotificationEmailOption": "📧 Email only - No banner",
    "ManageAlertsNotificationBothOption": "📧🌐 Browser + Email",
    "ManageAlertsCreatedDateFilterLabel": "Created Date",
    "ManageAlertsDateAllOption": "📅 All Dates",
    "ManageAlertsDateTodayOption": "📅 Today",
    "ManageAlertsDateWeekOption": "📅 This Week",
    "ManageAlertsDateMonthOption": "📅 This Month",
    "ManageAlertsDateCustomOption": "📅 Custom Range",
    "ManageAlertsFromDateLabel": "From Date",
    "ManageAlertsToDateLabel": "To Date",
    "ManageAlertsClearFiltersButton": "Clear All Filters",
    "ManageAlertsSelectItemLabel": "Select alert {0}",
    "ManageAlertsNoTitleFallback": "[No Title Available]",
    "ManageAlertsNoDescriptionFallback": "[No Description Available]",
    "ManageAlertsTemplateBadge": "📄 Template",
    "ManageAlertsAlertBadge": "📢 Alert",
    "ManageAlertsLanguageBadge": "{0} languages",
    "ManageAlertsMultiLanguageList": "🌐 Multi-language ({0})",
    "ManageAlertsAllLanguagesLabel": "🌐 All Languages",
    "ManageAlertsPublishButtonLabel": "Publish",
    "ManageAlertsCreatedLabel": "Created",
    "ManageAlertsContentClassificationDescription": "Choose whether this is a live alert, draft, or reusable template",
    "ManageAlertsLanguageConfigurationLabel": "Language Configuration",
    "ManageAlertsSingleLanguageButton": "🌐 Single Language",
    "ManageAlertsMultiLanguageButton": "🗣️ Multi-Language",
    "ManageAlertsTargetLanguageDescription": "Choose which language audience this alert targets",
    "ManageAlertsDescriptionPlaceholder": "Provide detailed information about the alert...",
    "ManageAlertsDescriptionHelp": "Use the toolbar to format your message with rich text, links, lists, emojis, and images. Manage attachments below.",
    "ManageAlertsUploadedImagesSectionTitle": "Uploaded Images",
    "ManageAlertsAlertTypeDescription": "Select the visual style and category for this alert",
    "ManageAlertsPriorityDescription": "Set the importance level—affects styling and user attention",
    "ManageAlertsPinDescription": "Pinned alerts appear at the top and are more prominent",
    "ManageAlertsNotificationMethodLabel": "Notification Method",
    "ManageAlertsNotificationDescription": "Choose how users will be notified about this alert",
    "ManageAlertsLinkDescriptionInfo": "💡 Link descriptions are configured per language in the Multi-Language Content section above.",
    "ManageAlertsTargetSitesDescription": "Choose which SharePoint sites will display this alert.",
    "ManageAlertsSchedulingDescription": "Configure when this alert will be visible. Leave dates empty for immediate activation and manual control.",
    "ManageAlertsStartDateDescription": "When this alert becomes active",
    "ManageAlertsEndDateDescription": "When this alert expires",
    "ManageAlertsScheduleSummaryTitle": "Schedule Summary",
    "ManageAlertsScheduleImmediate": "⚡ Alert is active immediately and requires manual deactivation.",
    "ManageAlertsScheduleStartOnly": "📅 Alert activates on {0} and remains active until manually deactivated.",
    "ManageAlertsScheduleEndOnly": "⏰ Alert is active immediately until {0}.",
    "ManageAlertsScheduleWindow": "📅 Active from {0} to {1}.",
    "ManageAlertsScheduleTimezone": "🌍 All times are in your local time zone ({0}).",
    "ManageAlertsSavingChangesLabel": "Saving Changes...",
    "ManageAlertsSaveChangesButton": "Save Changes",
    "ManageAlertsLivePreviewTitle": "Live Preview",
    "ManageAlertsMultiLanguagePreviewHeading": "Multi-language Preview",
    "ManageAlertsMultiLanguagePreviewCurrentLanguage": "Currently previewing: {0}",
    "ManageAlertsMultiLanguagePreviewAvailableLanguages": "Available in {0} language(s): {1}",
    "ManageAlertsBulkDeleteDialogTitle": "Delete Alerts",
    "ManageAlertsBulkDeleteDialogMessage": "Are you sure you want to delete {0} alert(s)? This action cannot be undone.",
    "ManageAlertsBulkDeleteSuccessMessage": "Successfully deleted {0} alert(s)",
    "ManageAlertsBulkDeleteSuccessTitle": "Alerts Deleted",
    "ManageAlertsBulkDeleteErrorMessage": "Failed to delete some alerts. Please try again.",
    "ManageAlertsBulkDeleteErrorTitle": "Deletion Failed",
    "ManageAlertsDeleteDialogTitle": "Delete Alert",
    "ManageAlertsDeleteDialogMessage": "Are you sure you want to delete \"{0}\"? This action cannot be undone.",
    "ManageAlertsDeleteSuccessMessage": "Successfully deleted \"{0}\"",
    "ManageAlertsDeleteSuccessTitle": "Alert Deleted",
    "ManageAlertsDeleteErrorMessage": "Failed to delete alert. Please try again.",
    "ManageAlertsDeleteErrorTitle": "Deletion Failed",
    "ManageAlertsEditOpenErrorMessage": "Failed to open edit dialog. Please try again.",
    "ManageAlertsEditOpenErrorTitle": "Edit Failed",
    "ManageAlertsPublishDialogTitle": "Publish Draft",
    "ManageAlertsPublishDialogMessage": "Publish \"{0}\" as a live alert? It will be visible to users immediately.",
    "ManageAlertsPublishDialogConfirm": "Publish",
    "ManageAlertsPublishSuccessMessage": "Successfully published \"{0}\"",
    "ManageAlertsPublishSuccessTitle": "Draft Published",
    "ManageAlertsPublishErrorMessage": "Failed to publish draft. Please try again.",
    "ManageAlertsPublishErrorTitle": "Publish Failed",
    "ManageAlertsSubmitDialogTitle": "Submit for Review",
    "ManageAlertsSubmitDialogMessage": "Submit \"{0}\" for review?",
    "ManageAlertsSubmitDialogConfirm": "Submit",
    "ManageAlertsSubmitSuccessMessage": "Successfully submitted \"{0}\" for review",
    "ManageAlertsSubmitSuccessTitle": "Alert Submitted",
    "ManageAlertsSubmitErrorMessage": "Failed to submit alert. Please try again.",
    "ManageAlertsSubmitErrorTitle": "Submission Failed",
    "ManageAlertsApproveDialogTitle": "Approve Alert",
    "ManageAlertsApproveDialogMessage": "Approve \"{0}\"? It will become visible to users based on scheduling.",
    "ManageAlertsApproveDialogConfirm": "Approve",
    "ManageAlertsApproveSuccessMessage": "Successfully approved \"{0}\"",
    "ManageAlertsApproveSuccessTitle": "Alert Approved",
    "ManageAlertsApproveErrorMessage": "Failed to approve alert. Please try again.",
    "ManageAlertsApproveErrorTitle": "Approval Failed",
    "ManageAlertsRejectDialogTitle": "Reject Alert",
    "ManageAlertsRejectDialogMessage": "Enter rejection notes for \"{0}\" (optional):",
    "ManageAlertsRejectDialogConfirm": "Reject",
    "ManageAlertsRejectDialogLabel": "Notes",
    "ManageAlertsRejectDialogPlaceholder": "Enter rejection notes...",
    "ManageAlertsRejectSuccessMessage": "Rejected \"{0}\"",
    "ManageAlertsRejectSuccessTitle": "Alert Rejected",
    "ManageAlertsRejectErrorMessage": "Failed to reject alert. Please try again.",
    "ManageAlertsRejectErrorTitle": "Rejection Failed",
    "ManageAlertsUpdateSuccessMessage": "Alert updated successfully!",
    "ManageAlertsUpdateSuccessTitle": "Update Complete",
    "ManageAlertsUpdateErrorMessage": "Failed to update alert. Please try again.",
    "ManageAlertsUpdateErrorTitle": "Update Failed",
    "ManageAlertsApprovalStatusLabel": "Approval Status",
    "ManageAlertsApprovalAnyStatusOption": "Any Status",
    "ManageAlertsApprovalDraftOption": "✏️ Draft",
    "ManageAlertsApprovalPendingOption": "⏳ Pending Review",
    "ManageAlertsApprovalApprovedOption": "✅ Approved",
    "ManageAlertsApprovalRejectedOption": "❌ Rejected",
    "ManageAlertsSubmitForReviewTitle": "Submit for Review",
    "ManageAlertsSubmitForReviewButton": "Submit",
    "ManageAlertsApproveButton": "Approve",
    "ManageAlertsRejectButton": "Reject",
    "ManageAlertsPinnedBadge": "📌 PINNED",
    "ManageAlertsContentStatusPending": "⏳ Pending",
    "ManageAlertsContentStatusRejected": "❌ Rejected",
    "ManageAlertsContentStatusDraft": "✏️ Draft",
    "FailedToLoadSiteInformation": "Failed to load site information",
    "LanguagesUpdatedSuccessfully": "Languages updated successfully for {0}",
    "FailedToUpdateLanguages": "Failed to update languages for {0}",
    "AlertsListCreatedSuccessfully": "Alerts list created successfully on {0}",
    "FailedToCreateAlertsList": "Failed to create alerts list",
    "HomeSite": "Home Site",
    "HomeSiteDescription": "Alerts shown on all sites in the tenant",
    "HomeSiteScope": "Shown on all sites",
    "HubSite": "Hub Site",
    "HubSiteDescription": "Alerts shown on hub and connected sites",
    "HubSiteScope": "Shown on hub and connected sites",
    "CurrentSiteDescription": "Alerts shown only on this site",
    "SiteScope": "Shown only on this site",
    "ListExistsAndAccessible": "List exists and accessible",
    "ListExistsNoAccess": "List exists but no access",
    "ListNotExistsCanCreate": "List not found - can create",
    "ListNotExistsCannotCreate": "List not found - cannot create",
    "AlertListsManagement": "Alert Lists Management",
    "LoadingSiteInformation": "Loading site information...",
    "ManageAlertListsDescription": "Manage alert lists across your site hierarchy",
    "CreatingList": "Creating...",
    "CreateAlertsList": "Create Alerts List",
    "SelectLanguagesForList": "Select Languages for Alert List",
    "SelectLanguagesDescription": "Choose which languages to support for alerts on {0}. English is required and will always be included.",
    "SelectedLanguages": "Selected languages",
    "CreateWithSelectedLanguages": "Create with {0} languages",
    "ReadyForAlerts": "Ready for alerts",
    "ViewEditLanguages": "Languages",
    "ManageLanguagesForList": "Manage Languages for Alert List",
    "ManageLanguagesDescription": "Manage which languages are supported for alerts on {0}. English is required and will always be included.",
    "UpdateLanguages": "Update Languages",
    "AlertHierarchy": "Alert Display Hierarchy",
    "AlertHierarchyDescription": "Alerts are displayed based on site hierarchy: Home Site alerts appear everywhere, Hub Site alerts appear on hub and connected sites, and Site alerts appear only on the specific site.",
    // Priority Levels
    "PriorityLow": "Matala",
    "PriorityMedium": "Keskitaso",
    "PriorityHigh": "Korkea",
    "PriorityCritical": "Kriittinen",
    
    // Status Types
    "StatusActive": "Aktiivinen",
    "StatusExpired": "Vanhentunut",
    "StatusScheduled": "Ajastettu",
    "StatusInactive": "Ei-aktiivinen",
    
    // Notification Types
    "NotificationNone": "Ei mitään",
    "NotificationBrowser": "Selain",
    "NotificationEmail": "Sähköposti",
    "NotificationBoth": "Molemmat",
    
    // Alert Types
    "AlertTypeInfo": "Tieto",
    "AlertTypeWarning": "Varoitus",
    "AlertTypeMaintenance": "Huolto",
    "AlertTypeInterruption": "Keskeytys",
    
    // User Interface
    "ShowMore": "Näytä lisää",
    "ShowLess": "Näytä vähemmän",
    "ViewDetails": "Näytä tiedot",
    "Expand": "Laajenna",
    "Collapse": "Tiivistä",
    "Preview": "Esikatselu",
    "Templates": "Mallit",
    "CustomizeColors": "Mukauta värit",
    
    // Site Selection
    "SelectSites": "Valitse sivustot",
    "CurrentSite": "Nykyinen sivusto",
    "AllSites": "Kaikki sivustot",
    "HubSites": "Keskussivustot",
    "RecentSites": "Viimeaikaiset sivustot",
    "FollowedSites": "Seuratut sivustot",
    
    // Permissions and Errors
    "InsufficientPermissions": "Riittämättömät oikeudet tämän toiminnon suorittamiseen",
    "PermissionDeniedCreateLists": "Käyttäjällä ei ole oikeuksia SharePoint-listojen luomiseen",
    "PermissionDeniedAccessLists": "Käyttäjällä ei ole oikeuksia SharePoint-listojen käyttämiseen",
    "ListsNotFound": "SharePoint-listoja ei ole olemassa eikä niitä voida luoda",
    "InitializationFailed": "SharePoint-yhteyden alustaminen epäonnistui",
    "ConnectionError": "Yhteysvirhe tapahtui",
    "SaveError": "Virhe tallennuksen aikana",
    "LoadError": "Virhe tietojen latauksen aikana",
    
    // User Friendly Messages
    "NoAlertsMessage": "Hälytyksiä ei ole tällä hetkellä saatavilla",
    "AlertsLoadingMessage": "Ladataan hälytyksiä...",
    "AlertCreatedSuccess": "Hälytys luotu onnistuneesti",
    "AlertUpdatedSuccess": "Hälytys päivitetty onnistuneesti",
    "AlertDeletedSuccess": "Hälytys poistettu onnistuneesti",
    "SettingsSavedSuccess": "Asetukset tallennettu onnistuneesti",
    
    // Date and Time
    "CreatedBy": "Luotu",
    "CreatedOn": "Luotu",
    "LastModified": "Viimeksi muokattu",
    "Never": "Ei koskaan",
    "Today": "Tänään",
    "Yesterday": "Eilen",
    "Tomorrow": "Huomenna",
    
    // Validation Messages
    "FieldRequired": "Tämä kenttä on pakollinen",
    "InvalidUrl": "Anna kelvollinen URL",
    "InvalidDate": "Anna kelvollinen päivämäärä",
    "InvalidEmail": "Anna kelvollinen sähköpostiosoite",
    "TitleTooLong": "Otsikko on liian pitkä (enintään 255 merkkiä)",
    "DescriptionTooLong": "Kuvaus on liian pitkä (enintään 2000 merkkiä)",
    "TitleRequired": "Title is required",
    "DescriptionRequired": "Description is required",
    "AlertTypeRequired": "Alert type is required",
    "TitleMinLength": "Title must be at least 3 characters",
    "TitleMaxLength": "Title cannot exceed 100 characters",
    "DescriptionMinLength": "Description must be at least 10 characters",
    "InvalidUrlFormat": "Please enter a valid URL",
    "LinkDescriptionRequired": "Link description is required when URL is provided",
    "EndDateMustBeAfterStartDate": "End date must be after start date",
    "AtLeastOneSiteRequired": "At least one target site must be selected",
    
    // Rich Media
    "UploadImage": "Lataa kuva",
    "RemoveImage": "Poista kuva",
    "ImageAltText": "Kuvan vaihtoehtoteksti",
    "VideoUrl": "Videon URL",
    "EmbedCode": "Upotuskoodi",
    
    // Accessibility
    "CloseDialog": "Sulje dialogi",
    "OpenSettings": "Avaa asetukset",
    "ExpandAlert": "Laajenna hälytys",
    "CollapseAlert": "Tiivistä hälytys",
    "AlertActions": "Hälytystoiminnot",
    "PinAlert": "Kiinnitä hälytys",
    "UnpinAlert": "Poista hälytyksen kiinnitys",

    // Alert UI
    "AlertHeaderPriorityTooltip": "Priority: {0}",
    "AttachmentsHeader": "📎 Attachments ({0})",
    "FileSizeKilobytes": "{0} KB",
    "FileSizeMegabytes": "{0} MB",
    "AlertActionsOpenLink": "Open link",
    "AlertActionsPrevious": "Previous alert",
    "AlertActionsNext": "Next alert",
    "AlertActionsDismiss": "Dismiss alert",
    "AlertActionsHideForever": "Hide alert forever",
    "AlertCarouselCounter": "{0} of {1}",
    "DefaultAlertTypeName": "Default",
    "AlertsLoadErrorTitle": "Unable to load alerts",
    "AlertsLoadErrorFallback": "An error occurred while loading alerts. Please try refreshing the page or contact your administrator if the problem persists.",

    // Site Selector
    "SiteSelectorPermissionOwner": "Owner",
    "SiteSelectorPermissionFullControl": "Full Control",
    "SiteSelectorPermissionCanEdit": "Can Edit",
    "SiteSelectorPermissionDesigner": "Designer",
    "SiteSelectorPermissionReadOnly": "Read Only",
    "SiteSelectorLoading": "Loading available sites...",
    "SiteSelectorQuickSelectionTitle": "Quick Selection",
    "SiteSelectorCurrentSiteOnly": "Current Site Only",
    "SiteSelectorHubScope": "This Hub ({0} sites)",
    "SiteSelectorOrganizationHome": "Organization Home",
    "SiteSelectorRecentSites": "Recent Sites ({0})",
    "SiteSelectorSearchPlaceholder": "Search sites by name or URL...",
    "SiteSelectorFiltersLabel": "Filters",
    "SiteSelectorShowWritable": "Show only sites where I can create alerts",
    "SiteSelectorSiteTypeLabel": "Site Type:",
    "SiteSelectorSiteTypeAll": "All Sites",
    "SiteSelectorSiteTypeHub": "Hub Sites",
    "SiteSelectorSiteTypeTeam": "Team Sites",
    "SiteSelectorSiteTypeCommunication": "Communication Sites",
    "SiteSelectorSiteTypeHome": "Home Sites",
    "SiteSelectorNoResultsTitle": "No sites found",
    "SiteSelectorNoResultsDescription": "Try adjusting your search terms or filters.",
    "SiteSelectorWritableFilterHint": "You may need to disable the 'writable only' filter to see more sites.",
    "SiteSelectorSiteSingular": "site",
    "SiteSelectorSitePlural": "sites",
    "SiteSelectorSelected": "selected",
    "SiteSelectorMaxSelection": "(max {0})",

    // Multi-Language Content Editor
    "MultiLanguageEditorAddLanguagesLabel": "Add Languages:",
    "MultiLanguageEditorAllLanguagesAdded": "All available languages have been added",
    "MultiLanguageEditorIncompleteBadge": "Incomplete",
    "MultiLanguageEditorRemoveButton": "Remove",
    "MultiLanguageEditorTitleLabel": "Title",
    "MultiLanguageEditorTitlePlaceholder": "Enter alert title in {0}...",
    "MultiLanguageEditorDescriptionLabel": "Description",
    "MultiLanguageEditorDescriptionPlaceholder": "Enter alert description in {0}...",
    "MultiLanguageEditorLinkDescriptionLabel": "Link Description",
    "MultiLanguageEditorLinkDescriptionPlaceholder": "Enter link description in {0}...",
    "MultiLanguageEditorNoLanguagesTitle": "No Languages Selected",
    "MultiLanguageEditorNoLanguagesDescription": "Add languages above to create multi-language content",
    "MultiLanguageEditorSummaryTitle": "Content Summary:",
    "MultiLanguageEditorSummaryComplete": "✓ Complete",
    "MultiLanguageEditorSummaryIncomplete": "⚠ Incomplete",
    "MultiLanguageEditorLanguageCount": "{0} languages",
    "MultiLanguageEditorTranslateAllMissing": "Translate all missing",
    "MultiLanguageEditorNoMissingTranslations": "All language variants already have title and description.",
    "MultiLanguageEditorFallbackLabel": "Use this language as fallback for other users",
    "TranslationStatusLabel": "Translation Status",
    "TranslationStatusDescription": "Track the state of this language variant",
    "TranslationStatusDraft": "Draft",
    "TranslationStatusInReview": "In Review",
    "TranslationStatusApproved": "Approved",
    "LanguagePolicyInheritanceHint": "Empty fields will inherit from {0}.",

    // Language Policy
    "LanguagePolicyTitle": "Language Policy",
    "LanguagePolicyDescription": "Configure translation rules, fallback behavior, and workflow requirements for multi-language alerts.",
    "LanguagePolicyFallbackLanguageLabel": "Fallback Language",
    "LanguagePolicyFallbackLanguageDescription": "Used when a user’s preferred language is not available.",
    "LanguagePolicyFallbackTenantDefault": "Tenant default language",
    "LanguagePolicyCompletenessRuleLabel": "Translation Completeness",
    "LanguagePolicyCompletenessRuleDescription": "Choose how complete translations must be before saving or publishing.",
    "LanguagePolicyCompletenessAll": "Require all selected languages to be complete",
    "LanguagePolicyCompletenessAtLeastOne": "Require at least one complete language",
    "LanguagePolicyCompletenessDefault": "Require the default language to be complete",
    "LanguagePolicyRequireLinkDescriptionLabel": "Require link descriptions when a URL is provided",
    "LanguagePolicyRequireLinkDescriptionDescription": "Ensures localized link descriptions are provided for each language when links are used.",
    "LanguagePolicyPreventDuplicatesLabel": "Prevent duplicate language variants",
    "LanguagePolicyPreventDuplicatesDescription": "Block saving when the same language is added more than once.",
    "LanguagePolicyInheritanceEnable": "Enable field inheritance",
    "LanguagePolicyInheritanceDescription": "Allow missing fields to inherit from the fallback language.",
    "LanguagePolicyInheritanceTitleField": "Inherit Title",
    "LanguagePolicyInheritanceDescriptionField": "Inherit Description",
    "LanguagePolicyInheritanceLinkDescriptionField": "Inherit Link Description",
    "LanguagePolicyWorkflowEnable": "Enable translation workflow",
    "LanguagePolicyWorkflowDescription": "Track translation status for each language variant.",
    "LanguagePolicyWorkflowDefaultStatusLabel": "Default Translation Status",
    "LanguagePolicyWorkflowRequireApproved": "Require Approved status to display",
    "LanguagePolicyWorkflowRequireApprovedDescription": "Hide translation variants that are not approved.",
    "LanguagePolicySaveButton": "Save Language Policy",
    "LanguagePolicySaving": "Saving...",
    "LanguagePolicySavedSuccess": "Language policy saved",
    "LanguagePolicySavedFailed": "Failed to save language policy",

    // Language Manager
    "LanguageManagerTitle": "Multi-Language Field Management",
    "LanguageManagerDescription": "Select languages to add multi-language content fields to your alert lists. Fields will be created for Title, Description, and Link Description in each selected language.",
    "LanguageManagerAvailableLanguages": "Available Languages",
    "LanguageManagerActiveCount": "{0} active",
    "LanguageManagerActiveCountWithPending": "{0} active, {1} updating",
    "LanguageManagerLoading": "Loading...",
    "LanguageManagerLoadingSupport": "Loading language support...",
    "LanguageManagerUpdating": "Updating...",
    "LanguageManagerActive": "Active",
    "LanguageManagerLoadFailedDefault": "Could not load language support. Using site default: {0}",
    "LanguageManagerDefaultLanguageProtected": "{0} is the site's default language and cannot be removed.",
    "LanguageManagerAddedSuccess": "Added {0} language support successfully!",
    "LanguageManagerRemovedSuccess": "Removed {0} language support and columns.",
    "LanguageManagerUpdateFailed": "Failed to update language support for {0}.",

    // Alert Templates
    "AlertTemplatesTemplateDescription": "Template based on \"{0}\"",
    "AlertTemplatesCategoryAll": "All Templates",
    "AlertTemplatesCategoryMaintenance": "Maintenance",
    "AlertTemplatesCategoryInformation": "Information",
    "AlertTemplatesCategoryEmergency": "Emergency",
    "AlertTemplatesCategoryInterruption": "Interruption",
    "AlertTemplatesCategoryTraining": "Training",
    "AlertTemplatesCategoryAnnouncements": "Announcements",
    "AlertTemplatesHeaderTitle": "Choose a Template",
    "AlertTemplatesHeaderDescription": "Start with a pre-configured template and customize it to your needs",
    "AlertTemplatesSearchPlaceholder": "Search templates...",
    "AlertTemplatesUseTemplate": "Use Template →",
    "AlertTemplatesLoadingTitle": "Loading Templates...",
    "AlertTemplatesLoadingDescription": "Fetching templates from SharePoint",
    "AlertTemplatesNoResultsTitle": "No templates found",
    "AlertTemplatesNoResultsDescription": "Try adjusting your search terms or category filter",
    "AlertTemplatesEmptyTitle": "No templates available",
    "AlertTemplatesEmptyDescription": "Templates will be created automatically when alert lists are set up",
    "AlertTemplatesPinnedBadge": "PINNED",
    "AlertTemplatesNotifyBadge": "NOTIFY",
    "AlertTemplatesDefaultLinkDescription": "Learn more",

    // Attachments
    "AttachmentManagerDeleteConfirm": "Are you sure you want to delete \"{0}\"?",
    "AttachmentManagerTitle": "Attachments",
    "AttachmentManagerUploadingLabel": "Uploading...",
    "AttachmentManagerAddFilesButton": "Add Files",
    "AttachmentManagerSaveNotice": "Save the alert first to add attachments",
    "AttachmentManagerDropZoneInstruction": "Drag and drop files here or click \"Add Files\" button",
    "AttachmentManagerDropZoneHint": "{0} | Max {1}MB per file",
    "AttachmentManagerProgressTitle": "Uploading files...",
    "AttachmentManagerStatusCompleted": "✓ Completed",
    "AttachmentManagerStatusFailed": "✗ Failed",
    "AttachmentManagerDownloadTitle": "Download",
    "AttachmentManagerDeleteTitle": "Delete",
    "AttachmentManagerHelpText": "Allowed formats: {0} | Max size: {1}MB per file",
    "AttachmentManagerDeleteError": "Failed to delete attachment. Please try again.",
    "AttachmentManagerSaveAlertFirst": "Please save the alert first before adding attachments.",
    "AttachmentManagerUploadFailed": "Failed to upload some attachments. Please try again.",
    "AttachmentManagerInvalidFormat": "{0}: Invalid file format (allowed: {1})",
    "AttachmentManagerFileTooLarge": "{0}: File size exceeds {1}MB limit ({2}MB)",

    // Image Manager
    "ImageManagerDeleteConfirm": "Delete \"{0}\"? This cannot be undone.",
    "ImageManagerLoading": "Loading images...",
    "ImageManagerError": "Error: {0}",
    "ImageManagerEmpty": "No images uploaded yet",
    "ImageManagerHeaderTitle": "Uploaded Images ({0})",
    "ImageManagerCopyUrl": "Copy URL",
    "ImageManagerDeleteError": "Failed to delete image: {0}",
    "ImageManagerDeleteSuccess": "Image deleted successfully.",
    "ImageManagerCopySuccess": "Image URL copied to clipboard!",
    "ImageManagerCopyError": "Failed to copy URL",
    "ImageUploadFailure": "Image upload failed. Please try again.",
    "ImageUploadInvalidFile": "Please select a valid image file (PNG, JPG, GIF, or WebP).",

    // Repair Dialog
    "RepairDialogWarningMessage": "This action will modify your SharePoint list structure.",
    "RepairDialogActionsIntro": "The repair process will:",
    "RepairDialogRemoveColumns": "Remove outdated columns that are no longer needed",
    "RepairDialogAddColumns": "Add missing columns with current definitions",
    "RepairDialogUpdateColumns": "Update existing columns to match the latest schema",
    "RepairDialogProtectData": "Preserve all existing data and language-specific columns",
    "RepairDialogSafeProcess": "Safe Process:",
    "RepairDialogSafeProcessDescription": "This repair is designed to be non-destructive. Your existing alert data will be preserved, and language-specific columns will be kept intact.",
    "RepairDialogProgressTitle": "Repairing Alerts List...",
    "RepairDialogProgressDescription": "Please wait while we update your list structure. This may take a few minutes.",
    "RepairDialogResultSuccessTitle": "Repair Completed!",
    "RepairDialogResultFailureTitle": "Repair Failed",
    "RepairDialogRemovedColumnsTitle": "Removed Columns ({0})",
    "RepairDialogAddedColumnsTitle": "Added/Updated Columns ({0})",
    "RepairDialogWarningsTitle": "Warnings ({0})",
    "RepairDialogErrorsTitle": "Errors ({0})",
    "RepairDialogStartButton": "Start Repair",
    "RepairDialogCancelButton": "Cancel",
    "RepairDialogInProgressButton": "Repairing...",
    "RepairDialogCloseButton": "Close",
    "RepairDialogDialogTitleSuccess": "Repair Completed Successfully",
    "RepairDialogDialogTitleIssues": "Repair Completed with Issues",
    "RepairDialogDialogTitleProgress": "Repairing Alerts List",
    "RepairDialogTitle": "Repair Alerts List",
    "RepairDialogPleaseWait": "Please wait...",

    // Color Picker
    "ColorPickerSelectedColorAria": "Selected color: {0}",
    "ColorPickerPresetColorsTitle": "Preset Colors",
    "ColorPickerCustomColorTitle": "Custom Color",
    "ColorPickerApplyButton": "Apply",
    "ColorPickerSelectColorAria": "Select color {0}",

    // Emoji Picker
    "EmojiPickerButtonTitle": "Add emoji",
    "EmojiPickerButtonLabel": "Add Emoji",
    "EmojiPickerSearchPlaceholder": "Search emoji...",

    // Rich Text Editor
    "RichTextEditorLoadError": "Unable to load Rich Text editor",
    "RichTextEditorPlaceholder": "Enter your message...",

    // Progress Indicator
    "ProgressIndicatorTitle": "Progress",
    "ProgressIndicatorFailedSummary": "{0} of {1} steps failed",
    "ProgressIndicatorCompletedSummary": "{0} of {1} steps completed",
    "ProgressIndicatorError": "Error: {0}",

    // Alert Preview
    "AlertPreviewDefaultTitle": "Alert Title",
    "AlertPreviewDefaultDescription": "Alert description will appear here...",
    "AlertPreviewPinnedBadge": "📌 PINNED",
    "AlertPreviewTypeLabel": "Type:",
    "AlertPreviewPriorityLabel": "Priority:",
    "AlertPreviewBackgroundLabel": "Background:",
    "AlertPreviewTextColorLabel": "Text Color:",
    "AlertPreviewIconLabel": "Icon:",
    "AlertPreviewLinkPrefix": "🔗 {0}",

    // Error Boundary
    "ErrorBoundaryHeader": "Something went wrong in {0}",
    "ErrorBoundaryFallbackMessage": "An unexpected error occurred",
    "ErrorBoundaryIdLabel": "Error ID: {0}",
    "ErrorBoundaryRetryButton": "Try Again",
    "ErrorBoundaryAttemptsLeft": "attempts left",
    "ErrorBoundaryCopyButton": "Copy Error Details",
    "ErrorBoundaryReloadButton": "Reload Page",
    "ErrorBoundaryDevDetailsTitle": "Development Error Details",
    
    // Permission Status
    "PermissionStatusChecking": "Checking permissions...",
    "PermissionStatusAllGranted": "All required permissions are granted",
    "PermissionStatusMissingTitle": "Additional permissions required",
    "PermissionStatusSitesWriteRequired": "Sites.ReadWrite.All",
    "PermissionStatusSitesWriteDescription": "Required to create and manage alert lists across sites",
    "PermissionStatusMailRequired": "Mail.Send",
    "PermissionStatusMailDescription": "Required to send email notifications for critical alerts",
    "PermissionStatusShowDetails": "Show details",
    "PermissionStatusHideDetails": "Hide details",
    "PermissionStatusMissingList": "Missing permissions",
    "PermissionStatusAdminAction": "As a site admin, you can grant these permissions:",
    "PermissionStatusGrantPermissions": "Grant permissions in Azure AD",
    "PermissionStatusContactAdmin": "Please contact your SharePoint administrator to grant these permissions.",
    "ManageAlertsAlertTypeFromSourceSiteLabel": "{0} (from source site)",

    
    "ManageAlertsCrossSiteImagesNotice": "Images from other sites may not display due to cross-site permissions.",

    // Settings UX Enhancements
    "SettingsSaveAll": "Save Changes",
    "SettingsSaving": "Saving...",
    "SettingsDiscardChanges": "Discard Changes",
    "SettingsKeepEditing": "Keep Editing",
    "SettingsUnsavedChangesTitle": "Discard Unsaved Settings?",
    "SettingsUnsavedChangesMessage": "You have unsaved settings changes. Leave this tab and discard them?",
    "SettingsUnsavedChangesLabel": "Unsaved changes",
    "SettingsLastSavedLabel": "Last saved at {0}",
    "SettingsPreflightErrorsTitle": "Fix these issues before saving",
    "SettingsPreflightWarningsTitle": "Review before saving",
    "SettingsValidationCarouselNumber": "Carousel interval must be a whole number.",
    "SettingsValidationCarouselRange": "Carousel interval must be between {0} and {1} seconds.",
    "SettingsValidationEmail": "Email Service Account must be a valid email address.",
    "SettingsValidationAlertTypesJson": "Alert type configuration JSON is invalid.",
    "SettingsWarningNotificationsWithoutEmail": "Browser notifications are enabled without an email service account.",
    "SettingsReadOnlyWarning": "You can review settings, but saving requires Site Admin permissions.",
    "SettingsSectionPermissionsTitle": "Permissions & Readiness",
    "SettingsSectionAudienceTitle": "Audience & Targeting",
    "SettingsSectionIntegrationsTitle": "Integrations",
    "SettingsSectionExperienceTitle": "Experience",
    "SettingsSectionLocalizationTitle": "Localization",
    "SettingsSectionSetupTitle": "SharePoint Setup",
    "SettingsSectionMaintenanceTitle": "Maintenance",
    "SettingsEnableTargetSitesLabel": "Enable Target Site Selection",
    "SettingsEnableTargetSitesDescription": "Allow administrators to target specific sites for each alert.",
    "SettingsEnableNotificationsDescription": "Send browser notifications for high-priority alerts. Keep disabled if you want banners only.",
    "SettingsEmailServiceAccountLabel": "Email Service Account",
    "SettingsEmailServiceAccountPlaceholder": "alerts-noreply@yourtenant.onmicrosoft.com",
    "SettingsEmailServiceAccountDescription": "Service account used for Graph-based email notifications (Mail.Send required).",
    "SettingsSendTestEmailButton": "Send Test Email",
    "SettingsGraphUnavailableError": "Graph client is unavailable in this context.",
    "SettingsTestEmailSuccess": "Test email sent. Check your inbox.",
    "SettingsTestEmailFailed": "Failed to send test email. Verify Mail.Send permission and account configuration.",
    "SettingsCarouselEnabledLabel": "Enable Carousel Auto-Rotation",
    "SettingsCarouselEnabledDescription": "Automatically rotate between alerts when multiple alerts are visible.",
    "SettingsCarouselIntervalLabel": "Carousel Timer (seconds)",
    "SettingsCarouselIntervalDescription": "Time in seconds between automatic transitions.",
    "SettingsCheckingLists": "Checking SharePoint lists...",
    "SettingsMissingListsDescription": "Some required lists are missing and need to be created on this site.",
    "SettingsCurrentSiteLabel": "Current Site:",
    "SettingsMissingAlertsListItem": "Alerts list is missing (stores alert content).",
    "SettingsMissingTypesListItem": "AlertBannerTypes list is missing (stores styling definitions).",
    "SettingsInitialLanguagesTitle": "Select Languages for Initial Setup",
    "SettingsInitialLanguagesDescription": "Choose languages to provision now. You can add more later.",
    "SettingsInitialLanguagesHint": "English is always included and cannot be removed.",
    "SettingsCreatingLists": "Creating Lists...",
    "SettingsCreateMissingLists": "Create Missing Lists",
    "SettingsCreateMissingListsHelp": "Creates only missing lists on the current site.",
    "SettingsSetupCompleteTitle": "Setup Complete",
    "SettingsSetupCompleteDescription": "All required SharePoint lists are configured and ready to use.",
    "SettingsListMaintenanceTitle": "List Maintenance",
    "SettingsListMaintenanceDescription": "Repair list schema by removing obsolete columns and adding missing ones.",
    "SettingsStorageDescription": "Manage local cache and advanced settings import/export actions.",
    "SettingsClearCache": "Clear Alert Cache",
    "SettingsCacheCleared": "Alert cache cleared.",
    "SettingsResetCarousel": "Reset Carousel Settings",
    "SettingsCarouselResetSuccess": "Carousel settings reset to defaults.",
    "SettingsShowAdvanced": "Show Advanced",
    "SettingsHideAdvanced": "Hide Advanced",
    "SettingsExportButton": "Export Settings JSON",
    "SettingsImportButton": "Import Settings JSON",
    "SettingsResetToDefaults": "Reset to Defaults",
    "SettingsExportSuccess": "Settings exported.",
    "SettingsExportFailed": "Failed to export settings.",
    "SettingsImportSuccess": "Settings imported into the draft editor.",
    "SettingsImportFailed": "Failed to import settings JSON.",
    "SettingsProgressCheckListsName": "Checking existing lists",
    "SettingsProgressCheckListsDescription": "Verifying what lists need to be created.",
    "SettingsProgressCreateListsName": "Creating SharePoint lists",
    "SettingsProgressCreateListsDescription": "Setting up Alerts and AlertBannerTypes lists.",
    "SettingsProgressAddLanguageName": "Adding {0} language support",
    "SettingsProgressAddLanguageDescription": "Creating language-specific columns for {0}.",
    "SettingsProgressFinalizeName": "Finalizing setup",
    "SettingsProgressFinalizeDescription": "Completing configuration and verification.",
    "SettingsListsAlreadyExistMessage": "All required lists already exist on this site.",
    "SettingsListsAlreadyExistTitle": "Lists Already Exist",
    "SettingsListsCreatedTitle": "Lists Created Successfully",
    "SettingsAdditionalInformationTitle": "Additional Information",
    "SettingsContactAdministrator": "Contact Administrator",
    "AlertTypeIconLabel": "Icon",
    "AlertTypeChooseIconButton": "Choose Fluent UI Icon",
    "AlertTypeSelectedIconNameLabel": "Selected Icon Name",
    "AlertTypeSelectedIconNamePlaceholder": "Info",
    "AlertTypeSelectedIconNameDescription": "Selected Fluent UI icon name. You can still type a custom icon name.",
    "AlertTypeIconDialogTitle": "Select a Fluent UI Icon",
    "AlertTypeIconSearchLabel": "Search icons",
    "AlertTypeIconSearchPlaceholder": "Type icon name (e.g., Shield, Calendar, Megaphone)",
    "AlertTypeIconResultsCount": "{0} icon(s)",
    "AlertTypeIconNoResultsTitle": "No matching icons",
    "AlertTypeIconNoResultsDescription": "Try a different search term to find a Fluent UI icon.",
  }
});
